-- 코드를 입력하세요

# SELECT CAR_ID, START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID

SELECT CAR_ID,
        MAX(IF (DATE_FORMAT(START_DATE, '%Y-%m-%d') <= DATE_FORMAT('2022-10-16', '%Y-%m-%d') AND DATE_FORMAT('2022-10-16', '%Y-%m-%d') <= DATE_FORMAT(END_DATE, '%Y-%m-%d'), '대여중', '대여 가능')) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC