-- 코드를 입력하세요
SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') AS 'PUBLISHED_DATE'
FROM BOOK AS A, AUTHOR AS B
WHERE A.AUTHOR_ID = B.AUTHOR_ID AND CATEGORY = '경제'
ORDER BY A.PUBLISHED_DATE ASC